version: "3.0"
services:

  keycloak-server:
    image: jboss/keycloak
    volumes:
      - ~/repo/docker-playground/keycloak/data:/tmp
    ports:
      - "9999:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=123456
      - DB_VENDOR=H2
    networks:
      - docker-playground-network
      
networks:
  docker-playground-network:
